### ISSUE TITLE
Error compile for Arduino UNO

### ISSUE THREAD

**Issue by RivelinoDomingo** [ysard/PT6312_VFD_Arduino_Library#3]
`/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp: In function 'void VFD_writeString(const char*, bool)':
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:35:5: error: 'uint8_t' was not declared in this scope
     uint8_t lsb_byte;
     ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:36:13: error: expected ';' before 'msb_byte'
     uint8_t msb_byte;
             ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:39:14: error: 'grid_cursor' was not declared in this scope
         if ((grid_cursor == 3) || (grid_cursor == 4)) {
              ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:42:13: error: 'msb_byte' was not declared in this scope
             msb_byte = FONT[*string - 0x20][1];
             ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:42:24: error: 'FONT' was not declared in this scope
             msb_byte = FONT[*string - 0x20][1];
                        ^~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:47:17: error: 'lsb_byte' was not declared in this scope
                 lsb_byte = FONT[*string - 0x20][1];
                 ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:49:17: error: 'lsb_byte' was not declared in this scope
                 lsb_byte = 0;
                 ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:60:17: error: 'lsb_byte' was not declared in this scope
                 lsb_byte |= 1 << (VFD_COLON_SYMBOL_BIT - 1);
                 ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:60:35: error: 'VFD_COLON_SYMBOL_BIT' was not declared in this scope
                 lsb_byte |= 1 << (VFD_COLON_SYMBOL_BIT - 1);
                                   ^~~~~~~~~~~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:67:13: error: 'lsb_byte' was not declared in this scope
             lsb_byte = FONT[*string - 0x20][1];
             ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:67:24: error: 'FONT' was not declared in this scope
             lsb_byte = FONT[*string - 0x20][1];
                        ^~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:69:13: error: 'msb_byte' was not declared in this scope
             msb_byte = FONT[*string - 0x20][0];
             ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:78:21: error: 'lsb_byte' was not declared in this scope
         VFD_command(lsb_byte, false);
                     ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:78:9: error: 'VFD_command' was not declared in this scope
         VFD_command(lsb_byte, false);
         ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:79:21: error: 'msb_byte' was not declared in this scope
         VFD_command(msb_byte, false);
                     ^~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:82:9: error: 'grid_cursor' was not declared in this scope
         grid_cursor++;
         ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:87:5: error: 'VFD_CSSignal' was not declared in this scope
     VFD_CSSignal();
     ^~~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp: At global scope:
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:121:29: error: variable or field 'VFD_busySpinningCircle' declared void
 void VFD_busySpinningCircle(uint8_t address, uint8_t& frame_number, uint8_t& loop_number)
                             ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:121:29: error: 'uint8_t' was not declared in this scope
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:121:46: error: 'uint8_t' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t address, uint8_t& frame_number, uint8_t& loop_number)
                                              ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:121:55: error: 'frame_number' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t address, uint8_t& frame_number, uint8_t& loop_number)
                                                       ^~~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:121:69: error: 'uint8_t' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t address, uint8_t& frame_number, uint8_t& loop_number)
                                                                     ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_1_functions.cpp:121:78: error: 'loop_number' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t address, uint8_t& frame_number, uint8_t& loop_number)
                                                                              ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp: In function 'void VFD_writeString(const char*, bool)':
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:36:5: error: 'uint8_t' was not declared in this scope
     uint8_t chrset;
     ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:40:9: error: 'chrset' was not declared in this scope
         chrset = FONT[*string - 0x20][1];
         ^~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:40:18: error: 'FONT' was not declared in this scope
         chrset = FONT[*string - 0x20][1];
                  ^~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:44:31: error: 'grid_cursor' was not declared in this scope
         if (colon_symbol && ((grid_cursor == 3) || (grid_cursor == 5))) {
                               ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:46:29: error: 'VFD_COLON_SYMBOL_BIT' was not declared in this scope
             chrset |= 1 << (VFD_COLON_SYMBOL_BIT - 1);
                             ^~~~~~~~~~~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:54:9: error: 'VFD_command' was not declared in this scope
         VFD_command(chrset, false);
         ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:74:9: error: 'grid_cursor' was not declared in this scope
         grid_cursor++;
         ^~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:79:5: error: 'VFD_CSSignal' was not declared in this scope
     VFD_CSSignal();
     ^~~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp: At global scope:
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:110:29: error: variable or field 'VFD_busySpinningCircle' declared void
 void VFD_busySpinningCircle(uint8_t position, uint8_t& frame_number, uint8_t& loop_number)
                             ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:110:29: error: 'uint8_t' was not declared in this scope
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:110:47: error: 'uint8_t' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t position, uint8_t& frame_number, uint8_t& loop_number)
                                               ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:110:56: error: 'frame_number' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t position, uint8_t& frame_number, uint8_t& loop_number)
                                                        ^~~~~~~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:110:70: error: 'uint8_t' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t position, uint8_t& frame_number, uint8_t& loop_number)
                                                                      ^~~~~~~
/home/rivelino/Arduino/libraries/PT6312_VFD_Arduino_Library-master/src/display_variants/variant_2_functions.cpp:110:79: error: 'loop_number' was not declared in this scope
 void VFD_busySpinningCircle(uint8_t position, uint8_t& frame_number, uint8_t& loop_number)
                                                                               ^~~~~~~~~~~

exit status 1

Compilation error: exit status 1`

I was trying to compile the test_attiny_vfd.ino example on my Arduino UNO, I couldn't work around the problem.

**Comment by ysard** [comment]
Hi, yeah I can confirm this problem.
My dev env has not the same structure than the one released on Arduino repository.
I will fix that.

For now, you can just copy the content of your Arduino folder: `~/Arduino/libraries/PT6312/src` and put it in `~/Arduino/libraries/PT6312/` (one level above).
Then restart the Arduino IDE, it should be OK.

**Comment by RivelinoDomingo** [comment]
Thank you, I tried the temporary solution you proposed but it didn't work.

`/home/rivelino/Arduino/libraries/PT6312/src/display_variants/variant_1_functions.cpp: In function 'void VFD_writeString(const char*, bool)':
/home/rivelino/Arduino/libraries/PT6312/src/display_variants/variant_1_functions.cpp:35:5: error: 'uint8_t' was not declared in this scope
     uint8_t lsb_byte`

library folder:
`rivelino@rivelino-PC:~/Arduino/libraries/PT6312$ pwd 
/home/rivelino/Arduino/libraries/PT6312
rivelino@rivelino-PC:~/Arduino/libraries/PT6312$ ls 
display_variants  examples  global.h  library.properties  LICENSE  PT6312.cpp  PT6312.h  README.md  src`

**Comment by ysard** [comment]
It should be ok now, let's see the publish result starting around 2:25 am GMT+2.

**Comment by RivelinoDomingo** [comment]
Here it worked well with this review, although I am not having success in
my studies, but now I am trying a solution with your library.

Em sex, 26 de mai de 2023 20:42, ysard ***@***.***> escreveu:

**Comment by ysard** [comment]
Ok, thanks for the test.
Yeah, building a font for a specific device can be a tedious work.
